
### Create User
POST http://localhost:80/api/create
Content-Type: application/json

{
  "userId": "132",
  "userName": "John Dantist2",
  "items": [
      {
        "itemId": "item1",
        "count": 1
      },
    {
      "itemId": "item2",
      "count": 2
    }
  ],
  "unlocked": [
    {
      "itemId": "item1"
    }
  ]
}
